In [1]:
import numpy as np 
import pandas as pd 
import scipy.stats
cereal = pd.read_csv("https://raw.githubusercontent.com/benvictoria17/DataAnalytics/main/dataset/80%20Cereals-%20Nutrition%20data%20on%2080%20cereal%20products/cereal.csv")

In [2]:
cereal.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,106.883117,2.545455,1.012987,159.675325,2.151948,14.597403,6.922078,96.077922,28.246753,2.207792,1.029610,0.821039,42.665705
std,19.484119,1.094790,1.006473,83.832295,2.383364,4.278956,4.444885,71.286813,22.342523,0.832524,0.150477,0.232716,14.047289
min,50.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,130.000000,1.000000,12.000000,3.000000,40.000000,25.000000,1.000000,1.000000,0.670000,33.174094
50%,110.000000,3.000000,1.000000,180.000000,2.000000,14.000000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.400208
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.828392
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [3]:
scipy.stats.chisquare(f_obs= cereal["fat"].value_counts())

Power_divergenceResult(statistic=43.1948051948052, pvalue=9.428134112602245e-09)

In [4]:
scipy.stats.chisquare(f_obs= cereal["fiber"].value_counts())

Power_divergenceResult(statistic=89.97402597402598, pvalue=4.994883211257597e-14)

In [5]:
acrossTab = pd.crosstab( cereal["fat"], cereal["fiber"])
acrossTab

fiber,0.0,1.0,1.5,2.0,2.5,2.7,3.0,4.0,5.0,6.0,9.0,10.0,14.0
fat,,,,,,,,,,,,,
0,6,10,0,1,0,0,6,1,2,0,0,0,1
1,11,4,1,4,0,0,4,2,1,1,1,1,0
2,1,2,2,4,1,1,2,0,1,0,0,0,0
3,1,0,0,0,0,0,3,1,0,0,0,0,0
5,0,0,0,1,0,0,0,0,0,0,0,0,0

In [6]:
scipy.stats.chi2_contingency(acrossTab)

(50.534493177387915,
 0.3736986641955443,
 48,
 array([[6.66233766, 5.61038961, 1.05194805, 3.50649351, 0.35064935,
         0.35064935, 5.25974026, 1.4025974 , 1.4025974 , 0.35064935,
         0.35064935, 0.35064935, 0.35064935],
        [7.4025974 , 6.23376623, 1.16883117, 3.8961039 , 0.38961039,
         0.38961039, 5.84415584, 1.55844156, 1.55844156, 0.38961039,
         0.38961039, 0.38961039, 0.38961039],
        [3.45454545, 2.90909091, 0.54545455, 1.81818182, 0.18181818,
         0.18181818, 2.72727273, 0.72727273, 0.72727273, 0.18181818,
         0.18181818, 0.18181818, 0.18181818],
        [1.23376623, 1.03896104, 0.19480519, 0.64935065, 0.06493506,
         0.06493506, 0.97402597, 0.25974026, 0.25974026, 0.06493506,
         0.06493506, 0.06493506, 0.06493506],
        [0.24675325, 0.20779221, 0.03896104, 0.12987013, 0.01298701,
         0.01298701, 0.19480519, 0.05194805, 0.05194805, 0.01298701,
         0.01298701, 0.01298701, 0.01298701]]))