In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go
import plotly.offline as py
import plotly.express as px

In [3]:
nRowsRead = 1000 
df = pd.read_csv('https://raw.githubusercontent.com/benvictoria17/DataAnalytics/main/dataset/Cereals%20Usage%20by%20Brewers/brewers.csv', delimiter=';', encoding = "ISO-8859-1", nrows = nRowsRead)
df.dataframeName = 'brewers.csv'
nRow, nCol = df.shape
print(f'There are {nRow} rows and {nCol} columns')
df.head()

There are 222 rows and 13 columns

,YEAR,MONTH,TOTAL_BARLEY_USAGE,BARLEY_USED_FOR_MALTING,BARLEY_USED_AS_STRAIGHT_GRAIN_FOR_BREWING_DISTILLING,SALES_OF_BARLEY_AND_BARLEY_SCREENINGS,CLOSING_STOCKS_OF_BARLEY,TOTAL_WHEAT_USAGE,WHEAT_USED_FOR_ MALTING,WHEAT_USED_AS_STRAIGHT_GRAIN_FOR_BREWING_DISTILLING,CLOSING_STOCKS_OF_WHEAT,TOTAL_MAIZE_USED_AS_STRAIGHT_GRAIN_FOR_ BREWING_DISTILLING,CLOSING_STOCKS_OF_MAIZE
0,1997,1,142.0,136.9,5.0,5.2,1011.5,38.1,2.9,35.2,10.8,11.4,*
1,1997,2,141.3,135.0,6.3,5.3,992.4,51.3,2.1,49.2,13.4,12.4,*
2,1997,3,169.3,162.8,6.5,5.8,920.9,58.6,*,*,12.9,*,*
3,1997,4,159.1,152.9,6.2,4.9,845.8,50.4,*,*,13.5,*,*
4,1997,5,155.0,148.9,6.1,4.8,747.4,48.9,2,47,15.9,*,*

In [4]:
print ("Rows     : " ,df.shape[0])
print ("Columns  : " ,df.shape[1])
print ("\nFeatures : \n" ,df.columns.tolist())
print ("\nMissing values :  ", df.isnull().sum().values.sum())
print ("\nUnique values :  \n",df.nunique())

Rows     :  222
Columns  :  13

Features :
 ['YEAR', 'MONTH', 'TOTAL_BARLEY_USAGE', 'BARLEY_USED_FOR_MALTING', 'BARLEY_USED_AS_STRAIGHT_GRAIN_FOR_BREWING_DISTILLING', 'SALES_OF_BARLEY_AND_BARLEY_SCREENINGS', 'CLOSING_STOCKS_OF_BARLEY', 'TOTAL_WHEAT_USAGE', 'WHEAT_USED_FOR_ MALTING', 'WHEAT_USED_AS_STRAIGHT_GRAIN_FOR_BREWING_DISTILLING', 'CLOSING_STOCKS_OF_WHEAT', 'TOTAL_MAIZE_USED_AS_STRAIGHT_GRAIN_FOR_ BREWING_DISTILLING', 'CLOSING_STOCKS_OF_MAIZE']

Missing values :   0

Unique values :
 YEAR                                                           19
MONTH                                                          12
TOTAL_BARLEY_USAGE                                            179
BARLEY_USED_FOR_MALTING                                       178
BARLEY_USED_AS_STRAIGHT_GRAIN_FOR_BREWING_DISTILLING           49
SALES_OF_BARLEY_AND_BARLEY_SCREENINGS                          94
CLOSING_STOCKS_OF_BARLEY                                      218
TOTAL_WHEAT_USAGE                                             175
WHEAT_USED_FOR_ MALTING                                        34
WHEAT_USED_AS_STRAIGHT_GRAIN_FOR_BREWING_DISTILLING           114
CLOSING_STOCKS_OF_WHEAT                                        95
TOTAL_MAIZE_USED_AS_STRAIGHT_GRAIN_FOR_ BREWING_DISTILLING     15
CLOSING_STOCKS_OF_MAIZE                                        11
dtype: int64

In [ ]:
df.de