In [39]:
import numpy as np 
import pandas as pd 
from IPython.display import display
pd.options.display.max_columns = None

In [41]:
meta = pd.read_csv("https://raw.githubusercontent.com/benvictoria17/DataAnalytics/main/dataset/NBA%20playoff%202020/nba_playoffs_meta.csv")
meta

,team,team_short,conference,game_won,game_lose,conference_position,game_played,points_scored,points_missed,game_won_home,game_lose_home,game_won_away,game_lose_away
0,Milwaukee Bucks,MIL,EAST,56,17,1,73,8663,7927,30,5,26,12
1,Toronto Raptors,TOR,EAST,53,19,2,72,8118,7669,26,10,27,9
2,Boston Celtics,BOS,EAST,48,24,3,72,8183,7729,26,10,22,14
3,Indiana Pacers,IND,EAST,45,28,4,73,7989,7846,25,11,20,17
4,Miami Heat,MIA,EAST,44,29,5,73,8179,7964,29,7,15,22
5,Philadelphia 76ers,PHI,EAST,43,30,6,73,8084,7910,31,4,12,26
6,Brooklyn Nets,BKN,EAST,35,37,7,72,8048,8089,20,16,15,21
7,Orlando Magic,ORL,EAST,33,40,8,73,7831,7905,18,17,15,23
8,LA Lakers,LAL,WEST,52,19,1,71,8054,7643,25,10,27,9
9,LA Clippers,LAC,WEST,49,23,2,72,8377,7913,27,9,22,14
10,Denver Nuggets,DEN,WEST,46,27,3,73,8124,7970,26,11,20,16
11,Houston Rockets,HOU,WEST,44,28,4,72,8482,8269,24,12,20,16
12,Oklahoma City Thunder,OKC,WEST,44,28,5,72,8013,7835,23,14,21,14
13,Utah Jazz,UTA,WEST,44,28,6,72,7950,7807,23,12,21,16
14,Dallas Mavericks,DAL,WEST,43,32,7,75,8776,8405,20,18,23,14
15,Portland Trail Blazers,POR,WEST,35,39,8,74,8508,8593,21,15,14,24

In [42]:
games = pd.read_csv('https://raw.githubusercontent.com/benvictoria17/DataAnalytics/main/dataset/NBA%20playoff%202020/nba_playoffs_games.csv')
games

,series_id,home_team,away_team,home_points,away_points,round,game,score_home,score_away
0,1,MIL,ORL,110,122,1,1,0,0
1,1,MIL,ORL,111,96,1,2,0,1
2,1,ORL,MIL,107,121,1,3,1,1
3,1,ORL,MIL,106,121,1,4,1,2
4,1,MIL,ORL,118,104,1,5,3,1
...,...,...,...,...,...,...,...,...,...
61,12,DEN,LAC,107,113,2,3,1,1
62,12,DEN,LAC,85,96,2,4,1,2
63,12,LAC,DEN,105,111,2,5,3,1
64,12,DEN,LAC,111,98,2,6,3,2
65,12,LAC,DEN,89,104,2,7,3,3

In [43]:
df = pd.merge(games, meta, left_on='home_team', right_on='team_short')
df = df.drop(['team', 'team_short', 'conference'], axis=1)
df['home_team_win_ratio'] = df['game_won'] / df['game_played']
df['home_team_points_per_game'] = df['points_scored'] / df['game_played']
df['home_team_missed_points'] = df['points_missed'] / df['game_played']
df['home_team_home_win_ratio'] = df['game_won_home'] / (df['game_won_home'] + df['game_lose_home'])
df['home_team_away_win_ratio'] = df['game_won_away'] / (df['game_won_away'] + df['game_lose_away'])
df = df.drop(['game_won', 'game_lose', 'game_played', 'points_scored', 'points_missed', 'game_won_home', 'game_lose_home', 'game_won_away', 'game_lose_away'], axis=1)
df.columns = ['series_id', 'home_team', 'away_team', 'home_points', 'away_points', 'round', 'game', 'score_home', 'score_away', 'home_conference_position',
              'home_team_win_ratio', 'home_team_points_per_game', 'home_team_missed_points', 'home_team_home_win_ratio', 'home_team_away_win_ratio']
df = pd.merge(df, meta, left_on='away_team', right_on='team_short')
df = df.drop(['team', 'team_short', 'conference'], axis=1)
df['away_team_win_ratio'] = df['game_won'] / df['game_played']
df['away_team_points_per_game'] = df['points_scored'] / df['game_played']
df['away_team_missed_points'] = df['points_missed'] / df['game_played']
df['away_team_home_win_ratio'] = df['game_won_home'] / (df['game_won_home'] + df['game_lose_home'])
df['away_team_away_win_ratio'] = df['game_won_away'] / (df['game_won_away'] + df['game_lose_away'])
df = df.drop(['game_won', 'game_lose', 'game_played', 'points_scored', 'points_missed', 'game_won_home', 'game_lose_home', 'game_won_away', 'game_lose_away'], axis=1)
X = df.drop(['home_points', 'away_points'], axis=1)
y = df[['home_points', 'away_points']]
X

,series_id,home_team,away_team,round,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,MIL,ORL,1,1,0,0,1,0.767123,118.671233,108.589041,0.857143,0.684211,8,0.452055,107.273973,108.287671,0.514286,0.394737
1,1,MIL,ORL,1,2,0,1,1,0.767123,118.671233,108.589041,0.857143,0.684211,8,0.452055,107.273973,108.287671,0.514286,0.394737
2,1,MIL,ORL,1,5,3,1,1,0.767123,118.671233,108.589041,0.857143,0.684211,8,0.452055,107.273973,108.287671,0.514286,0.394737
3,9,MIL,MIA,2,1,0,0,1,0.767123,118.671233,108.589041,0.857143,0.684211,5,0.602740,112.041096,109.095890,0.805556,0.405405
4,9,MIL,MIA,2,2,0,1,1,0.767123,118.671233,108.589041,0.857143,0.684211,5,0.602740,112.041096,109.095890,0.805556,0.405405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,7,DEN,UTA,1,7,3,3,3,0.630137,111.287671,109.178082,0.702703,0.555556,6,0.611111,110.416667,108.430556,0.657143,0.567568
62,8,HOU,OKC,1,1,0,0,4,0.611111,117.805556,114.847222,0.666667,0.555556,5,0.611111,111.291667,108.819444,0.621622,0.600000
63,8,HOU,OKC,1,2,1,0,4,0.611111,117.805556,114.847222,0.666667,0.555556,5,0.611111,111.291667,108.819444,0.621622,0.600000
64,8,HOU,OKC,1,5,2,2,4,0.611111,117.805556,114.847222,0.666667,0.555556,5,0.611111,111.291667,108.819444,0.621622,0.600000
65,8,HOU,OKC,1,7,3,3,4,0.611111,117.805556,114.847222,0.666667,0.555556,5,0.611111,111.291667,108.819444,0.621622,0.600000

In [44]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score

In [45]:
Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("neg_root_mean_squared_error Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("neg_root_mean_squared_error Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

neg_root_mean_squared_error Home: -23.55 (+/- 18.33)
neg_root_mean_squared_error Away: -17.70 (+/- 7.82)

In [46]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,3,0.666667,113.652778,107.347222,0.722222,0.611111,5,0.60274,112.041096,109.09589,0.805556,0.405405

In [47]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  109
MIAMI points:  113

In [48]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -19.89 (+/- 12.58)
Score Away: -18.28 (+/- 7.10)

In [49]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,0,1,3,0.666667,113.652778,107.347222,0.722222,0.611111,5,0.60274,112.041096,109.09589,0.805556,0.405405

In [50]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  128
MIAMI points:  109

In [51]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -18.95 (+/- 10.68)
Score Away: -18.43 (+/- 8.00)

In [52]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,1,1,5,0.60274,112.041096,109.09589,0.805556,0.405405,3,0.666667,113.652778,107.347222,0.722222,0.611111

In [53]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  122
BOSTON points:  113

In [54]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -18.98 (+/- 10.21)
Score Away: -17.88 (+/- 5.37)

In [55]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,2,1,5,0.60274,112.041096,109.09589,0.805556,0.405405,3,0.666667,113.652778,107.347222,0.722222,0.611111

In [57]:
print('MIAMI points: ', int(model_home.predict(Xtr)[0]))
print('BOSTON points: ', int(model_away.predict(Xtr)[0]))

MIAMI points:  122
BOSTON points:  111

In [58]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'MIA'
Xtr['away_team'] = 'BOS'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -20.31 (+/- 8.45)
Score Away: -17.98 (+/- 6.58)

In [59]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'BOS']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'BOS']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'BOS']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'BOS']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,1,3,3,0.666667,113.652778,107.347222,0.722222,0.611111,5,0.60274,112.041096,109.09589,0.805556,0.405405

In [60]:
print('BOSTON points: ', int(model_home.predict(Xtr)[0]))
print('MIAMI points: ', int(model_away.predict(Xtr)[0]))

BOSTON points:  94
MIAMI points:  107

In [61]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'BOS'
Xtr['away_team'] = 'MIA'
X = pd.concat([X, Xtr])

X_semi = X.tail(5)
y_semi = y.tail(5)

In [62]:
X = X.head(66)
y = y.head(66)
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,1,0.732394,113.43662,107.647887,0.714286,0.75,3,0.630137,111.287671,109.178082,0.702703,0.555556

In [63]:
print('LAKERS points: ', int(model_home.predict(Xtr)[0]))
print('DENVER points: ', int(model_away.predict(Xtr)[0]))

LAKERS points:  120
DENVER points:  113

In [64]:
ytr = pd.DataFrame({'home_points': int(model_home.predict(Xtr)[0]), 'away_points': int(model_away.predict(Xtr)[0])}, index=[0])
y = pd.concat([y, ytr])
Xtr['home_team'] = 'LAL'
Xtr['away_team'] = 'DEN'
X = pd.concat([X, Xtr])

Xtr = X.drop(['series_id', 'home_team', 'away_team', 'round'], axis=1)
model_home = DecisionTreeRegressor(random_state=666)
target = y['home_points']
model_home.fit(Xtr, target)
scores = cross_val_score(model_home, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Home: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
target = y['away_points']
model_away = DecisionTreeRegressor(random_state=666)
model_away.fit(Xtr, target)
scores = cross_val_score(model_away, Xtr, target, cv=10, scoring='neg_root_mean_squared_error')
print("Score Away: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Score Home: -17.82 (+/- 11.29)
Score Away: -17.94 (+/- 6.04)

In [67]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,1,0,1,0.732394,113.43662,107.647887,0.714286,0.75,3,0.630137,111.287671,109.178082,0.702703,0.555556

In [70]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,1,1,3,0.630137,111.287671,109.178082,0.702703,0.555556,1,0.732394,113.43662,107.647887,0.714286,0.75

In [73]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 1
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,1,2,3,0.630137,111.287671,109.178082,0.702703,0.555556,1,0.732394,113.43662,107.647887,0.714286,0.75

In [76]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'DEN']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'DEN']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'DEN']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'DEN']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,3,1,1,0.732394,113.43662,107.647887,0.714286,0.75,3,0.630137,111.287671,109.178082,0.702703,0.555556

In [79]:
X = pd.concat([X, X_semi])
y = pd.concat([y, y_semi])
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 1}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,1,0,0,1,0.732394,113.43662,107.647887,0.714286,0.75,5,0.60274,112.041096,109.09589,0.805556,0.405405

In [84]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 2}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 0
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,2,0,1,1,0.732394,113.43662,107.647887,0.714286,0.75,5,0.60274,112.041096,109.09589,0.805556,0.405405

In [87]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,2,0,5,0.60274,112.041096,109.09589,0.805556,0.405405,1,0.732394,113.43662,107.647887,0.714286,0.75

In [88]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 3}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 0
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,3,2,0,5,0.60274,112.041096,109.09589,0.805556,0.405405,1,0.732394,113.43662,107.647887,0.714286,0.75

In [90]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 4}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 1
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,4,2,1,5,0.60274,112.041096,109.09589,0.805556,0.405405,1,0.732394,113.43662,107.647887,0.714286,0.75

In [93]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 5}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 2
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,5,2,2,1,0.732394,113.43662,107.647887,0.714286,0.75,5,0.60274,112.041096,109.09589,0.805556,0.405405

In [96]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 6}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 2
Xtr['home_conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,6,3,2,5,0.60274,112.041096,109.09589,0.805556,0.405405,1,0.732394,113.43662,107.647887,0.714286,0.75

In [99]:
Xtr = pd.DataFrame([], columns=['game', 'score_home', 'score_away', 'home_conference_position',
       'home_team_win_ratio', 'home_team_points_per_game',
       'home_team_missed_points', 'home_team_home_win_ratio',
       'home_team_away_win_ratio', 'conference_position',
       'away_team_win_ratio', 'away_team_points_per_game',
       'away_team_missed_points', 'away_team_home_win_ratio',
       'away_team_away_win_ratio'])

Xtr = Xtr.append({'game': 7}, ignore_index=True)
Xtr['game'] = Xtr['game'].astype(np.int8)
Xtr['score_home'] = 3
Xtr['score_away'] = 3
Xtr['home_conference_position'] = X[X['home_team'] == 'LAL']['home_conference_position'].values[0]
Xtr['home_team_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_win_ratio'].values[0]
Xtr['home_team_points_per_game'] = X[X['home_team'] == 'LAL']['home_team_points_per_game'].values[0]
Xtr['home_team_missed_points'] = X[X['home_team'] == 'LAL']['home_team_missed_points'].values[0]
Xtr['home_team_home_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_home_win_ratio'].values[0]
Xtr['home_team_away_win_ratio'] = X[X['home_team'] == 'LAL']['home_team_away_win_ratio'].values[0]
Xtr['conference_position'] = X[X['home_team'] == 'MIA']['home_conference_position'].values[0]
Xtr['away_team_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_win_ratio'].values[0]
Xtr['away_team_points_per_game'] = X[X['home_team'] == 'MIA']['home_team_points_per_game'].values[0]
Xtr['away_team_missed_points'] = X[X['home_team'] == 'MIA']['home_team_missed_points'].values[0]
Xtr['away_team_home_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_home_win_ratio'].values[0]
Xtr['away_team_away_win_ratio'] = X[X['home_team'] == 'MIA']['home_team_away_win_ratio'].values[0]
Xtr

,game,score_home,score_away,home_conference_position,home_team_win_ratio,home_team_points_per_game,home_team_missed_points,home_team_home_win_ratio,home_team_away_win_ratio,conference_position,away_team_win_ratio,away_team_points_per_game,away_team_missed_points,away_team_home_win_ratio,away_team_away_win_ratio
0,7,3,3,1,0.732394,113.43662,107.647887,0.714286,0.75,5,0.60274,112.041096,109.09589,0.805556,0.405405