In [4]:
import bq_helper

In [5]:
# create a helper object for our bigquery dataset
hacker_news = bq_helper.BigQueryHelper(active_project= "bigquery-public-data", 
                                       dataset_name = "hacker_news")

In [6]:
# print a list of all the tables in the hacker_news dataset
hacker_news.list_tables()

['comments', 'full', 'full_201510', 'stories']

In [7]:
# print information on all the columns in the "full" table
# in the hacker_news dataset
hacker_news.table_schema("full")

[SchemaField('title', 'string', 'NULLABLE', 'Story title', ()),
 SchemaField('url', 'string', 'NULLABLE', 'Story url', ()),
 SchemaField('text', 'string', 'NULLABLE', 'Story or comment text', ()),
 SchemaField('dead', 'boolean', 'NULLABLE', 'Is dead?', ()),
 SchemaField('by', 'string', 'NULLABLE', "The username of the item's author.", ()),
 SchemaField('score', 'integer', 'NULLABLE', 'Story score', ()),
 SchemaField('time', 'integer', 'NULLABLE', 'Unix time', ()),
 SchemaField('timestamp', 'timestamp', 'NULLABLE', 'Timestamp for the unix time', ()),
 SchemaField('type', 'string', 'NULLABLE', 'Type of details (comment, comment_ranking, poll, story, job, pollopt)', ()),
 SchemaField('id', 'integer', 'NULLABLE', "The item's unique id.", ()),
 SchemaField('parent', 'integer', 'NULLABLE', 'Parent comment ID', ()),
 SchemaField('descendants', 'integer', 'NULLABLE', 'Number of story or poll descendants', ()),
 SchemaField('ranking', 'integer', 'NULLABLE', 'Comment ranking', ()),
 SchemaField('deleted', 'boolean', 'NULLABLE', 'Is deleted?', ())]

In [8]:
# preview the first couple lines of the "full" table
hacker_news.head("full")

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,SummerOfCode/2011 - Mercurial,http://mercurial.selenic.com/wiki/SummerOfCode...,None,None,Ainab,2.0,1301680193,2011-04-01 17:49:53+00:00,story,2397215,NaN,0.0,None,None
1,None,None,Merging is still a pain with git. <i>Especiall...,None,Zev,NaN,1282084583,2010-08-17 22:36:23+00:00,comment,1612667,1612588.0,NaN,None,None
2,None,None,I have heard many people say that a &#x27;gree...,None,nickff,NaN,1461719808,2016-04-27 01:16:48+00:00,comment,11577147,11577117.0,NaN,None,None
3,None,None,While there's a resurgence of interest in ADA ...,None,SomeCallMeTim,NaN,1329614075,2012-02-19 01:14:35+00:00,comment,3608283,3608135.0,NaN,None,None
4,Hal Abelson Q&A (2011),http://codequarterly.com/2011/hal-abelson/,None,None,zootar,1.0,1390356278,2014-01-22 02:04:38+00:00,story,7100215,NaN,0.0,None,None

In [9]:
# preview the first ten entries in the by column of the full table
hacker_news.head("full", selected_columns="by", num_rows=10)

              by
0          Ainab
1            Zev
2         nickff
3  SomeCallMeTim
4         zootar
5     robterrell
6         mziulu
7     tathougies
8         mort96
9      kooshball

In [10]:
# this query looks in the full table in the hacker_news
# dataset, then gets the score column from every row where 
# the type column has "job" in it.
query = """SELECT score
            FROM `bigquery-public-data.hacker_news.full`
            WHERE type = "job" """

# check how big this query will be
hacker_news.estimate_query_size(query)

0.22408127784729004

In [11]:
# only run this query if it's less than 100 MB
hacker_news.query_to_pandas_safe(query, max_gb_scanned=0.1)

Query cancelled; estimated size of 0.22408127784729004 exceeds limit of 0.1 GB

In [12]:
# check out the scores of job postings (if the 
# query is smaller than 1 gig)
job_post_scores = hacker_news.query_to_pandas_safe(query)

In [13]:
# average score for job posts
job_post_scores.score.mean()

1.8798760626042743

In [14]:
# save our dataframe as a .csv 
job_post_scores.to_csv("job_post_scores.csv")