<a href="https://colab.research.google.com/github/benvictoria21/python-panda/blob/master/US_Elections_Starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

In [14]:
usa_2016_presidential_election_by_county = pd.read_csv('/content/drive/My Drive/BenCode/panda /data/US Elections Starter/us2016primaryresults.csv', sep=';')

In [15]:
usa_2016_presidential_election_by_county.head()

     state state_abbreviation  ... votes  fraction_votes
0  Vermont                 VT  ...    20           0.227
1  Vermont                 VT  ...    36           0.319
2  Vermont                 VT  ...    46           0.111
3  Vermont                 VT  ...    32           0.471
4  Vermont                 VT  ...     0           0.000

[5 rows x 8 columns]

In [4]:
usa_2016_presidential_election_by_county.shape

(3143, 159)

In [5]:
usa_2016_presidential_election_by_county.describe()

               Fips    Precincts  ...  Dem12 Frac2  Dem08 Frac2
count   3143.000000  3111.000000  ...  3112.000000  3112.000000
mean   30390.411709    54.927997  ...     0.392225     0.422473
std    15164.717720   172.872053  ...     0.150378     0.140607
min     1001.000000     1.000000  ...     0.034722     0.050314
25%    18178.000000    11.000000  ...     0.283582     0.319085
50%    29177.000000    20.000000  ...     0.379473     0.418391
75%    45082.000000    38.000000  ...     0.484609     0.513435
max    56045.000000  4988.000000  ...     0.939840     0.934008

[8 rows x 149 columns]

In [19]:
us_2016_primary_results = pd.read_csv('/content/drive/My Drive/BenCode/panda /data/US Elections Starter/us2016primaryresults.csv', sep=';')

In [8]:
us_2016_primary_results.head()

     state state_abbreviation  ... votes  fraction_votes
0  Vermont                 VT  ...    20           0.227
1  Vermont                 VT  ...    36           0.319
2  Vermont                 VT  ...    46           0.111
3  Vermont                 VT  ...    32           0.471
4  Vermont                 VT  ...     0           0.000

[5 rows x 8 columns]

In [17]:
us_2016_primary_results.shape

(24611, 8)